spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
  task:
    pool:
      core-pool-size: 2
      max-pool-size: 4
      keep-alive-seconds: 100
      queue-capacity: 100

udpReceivePort: 9898
